In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, LSTM, GRU, Dense, Embedding
import matplotlib.pyplot as plt


## Tokenization and Padding

In [2]:
# Toy dataset: positive (1) or negative (0) sentiment
sentences = [
    "I love cats",
    "I hate dogs",
    "I love dogs",
    "I dont like cats"
    
]

# Labels: 1 for positive sentiment, 0 for negative sentiment
labels = [1, 0, 1, 0]

# Tokenizing and converting sentences to sequences of integers
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=100)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

# Padding sequences to make them the same length
sequences = tf.keras.preprocessing.sequence.pad_sequences(sequences, padding='post')

# Convert labels to numpy array
labels = np.array(labels)

print(sequences)


[[1 2 3 0]
 [1 5 4 0]
 [1 2 4 0]
 [1 6 7 3]]


### Transforming words into vectors

In [3]:
# Embedding and sequence length parameters
# We limited the vocabulary to 100 words
vocab_size = 100 
# Size of word vectors
embedding_dim = 8 
# Maximum sequence length (4 in this case)
max_length = sequences.shape[1]  
print(max_length)

4


### RNN,LSTM,GRU Architectures

In [4]:
# RNN Model
def create_rnn_model():
    model = Sequential([
        Embedding(vocab_size, embedding_dim, input_length=max_length),
        SimpleRNN(4, return_sequences=False),  # Simple RNN with 4 units
        Dense(1, activation='sigmoid')
    ])
    return model


# LSTM Model
def create_lstm_model():
    model = Sequential([
        Embedding(vocab_size, embedding_dim, input_length=max_length),
        LSTM(4, return_sequences=False),  # LSTM with 4 units
        Dense(1, activation='sigmoid')
    ])
    return model

# GRU Model
def create_gru_model():
    model = Sequential([
        Embedding(vocab_size, embedding_dim, input_length=max_length),
        GRU(4, return_sequences=False),  # GRU with 4 units
        Dense(1, activation='sigmoid')
    ])
    return model


### Compiling and Fitting

In [5]:
# Compile and train RNN model
rnn_model = create_rnn_model()
rnn_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
rnn_model.fit(sequences, labels, epochs=10, verbose=1)
predictions = rnn_model.predict(sequences)
print(predictions)

# Compile and train LSTM model
lstm_model = create_lstm_model()
lstm_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
lstm_model.fit(sequences, labels, epochs=10, verbose=1)
predictions = lstm_model.predict(sequences)
print(predictions)

# Compile and train GRU model
gru_model = create_gru_model()
gru_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
gru_model.fit(sequences, labels, epochs=10, verbose=1)
predictions = gru_model.predict(sequences)
print(predictions)

Epoch 1/10


C:\Users\SNIGDHA\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - accuracy: 0.2500 - loss: 0.6992
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5000 - loss: 0.6951
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6911
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6871
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.7500 - loss: 0.6831
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.7500 - loss: 0.6790
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7500 - loss: 0.6751
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 1.0000 - loss: 0.6711
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 1.0000 - loss: 0.6671
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 1.0000 - loss: 0.6631
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 447ms/step
[[0.5169937 ]
 [0.4966131 ]
 [0.519343  ]
 [0.47007483]]
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 7s 7s/step - accuracy: 0.5000 - loss: 0.6922
Epoch

### Accessing Weights

In [6]:
# Accessing weights of the RNN layer
rnn_weights = rnn_model.layers[1].get_weights()
print("RNN Weights:", rnn_weights)

# Accessing weights of the LSTM layer
lstm_weights = lstm_model.layers[1].get_weights()
print("LSTM Weights:", lstm_weights)

# Accessing weights of the GRU layer
gru_weights = gru_model.layers[1].get_weights()
print("GRU Weights:", gru_weights)

RNN Weights: [array([[-0.4060081 ,  0.27840498, -0.71451336,  0.33100402],
       [ 0.50742716,  0.04213964, -0.3361757 , -0.3876614 ],
       [ 0.6259223 ,  0.56851006,  0.4462814 , -0.4751789 ],
       [-0.55546516, -0.6934783 ,  0.3622259 ,  0.31950608],
       [ 0.4596008 , -0.5749621 ,  0.540643  ,  0.48946893],
       [ 0.08506502,  0.65121543, -0.48659632, -0.2604892 ],
       [ 0.33120102, -0.6513586 , -0.3120959 ,  0.3680186 ],
       [-0.38231528, -0.52868444, -0.5719862 , -0.13219117]],
      dtype=float32), array([[ 0.01320834,  0.019065  ,  0.9575124 ,  0.28027177],
       [ 0.72361714,  0.57509   ,  0.07783502, -0.36633804],
       [-0.6974726 ,  0.6889203 ,  0.06102955, -0.24303006],
       [-0.10674852, -0.43514478,  0.26266176, -0.8422586 ]],
      dtype=float32), array([ 0.00367314,  0.00222081,  0.00033777, -0.0019007 ], dtype=float32)]
LSTM Weights: [array([[ 0.37561375,  0.18939202,  0.448658  ,  0.38507405,  0.04980252,
        -0.30250114, -0.08567487, -0.4666245